### ISSUE TITLE
Does not build: Inconsistent naming of Hal_defintions.h 

### ISSUE THREAD

**Issue by crashmatt** [trinamic/TrinamicOpenSourceVentilator-TOSV#1]
Does not build.
File named "Hal_Definitions.h"
Some files include "**HAL**_Definitions.h"

Attempted a pull request but had local git repo problems

**Comment by trinamic-ed** [comment]
Hi, thanks for the hint. I changed  "HAL_..." to "Hal_..." in three files. Thus, it should be fixed.

Please try the pull request with the submodule TOSV-Firmware only.
